---
- name: Format backup disk
  community.general.filesystem:
    dev: '{{ borg_repo_dev }}'
    fstype: xfs
    opts: -L backup
    state: present

- name: Mount backup disk
  ansible.posix.mount:
    src: LABEL=backup
    path: '{{ borg_repo_path }}'
    fstype: xfs
    opts: defaults
    dump: 0
    passno: 0
    boot: true
    state: mounted
